name: vcgen
version: 0.1.0.0
github: "yale-cpsc454/vcgen"
author: "William Hallahan"
maintainer: "ben.chaimberg@yale.edu"

extra-source-files:
  - src/Parser/Lexer.x
  - src/Parser/Parser.y

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/yale-cpsc454/vcgen#readme>

build-tools:
  - alex
  - happy

dependencies:
  - base >= 4.7 && < 5
  - array
  - directory

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  build-depends:
    - mtl
    - containers
    - bytestring
    - smtlib-backends
    - smtlib-backends-z3

executables:
  vcgen-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - vcgen
      - mtl
      - containers
      - bytestring
      - smtlib-backends
      - smtlib-backends-z3

tests:
  vcgen-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - vcgen
      - ghc
